//@version=4
study(title="[TVT] Multiple Moving Averages", shorttitle="TVT-MMA", overlay=true)

// === INPUTS ===
src = input(close)
use_ema = input(true, title="Use EMA over SMA?")

// Short Moving Averages
ma1   = input(3,title='Short MA-1')
ma2   = input(5,title='Short MA-2')
ma3   = input(7,title='Short MA-3')
ma4   = input(9,title='Short MA-4')
ma5   = input(11,title='Short MA-5')
ma6   = input(13,title='Short MA-6')
ma7   = input(15,title='Short MA-7')
ma8   = 21

lma5   = 50

blend_color = color.white

ma_series1 = use_ema ? sma(src, ma1) : ema(src, ma1)
ma_series2 = use_ema ? sma(src, ma2) : ema(src, ma2)
ma_series3 = use_ema ? sma(src, ma3) : ema(src, ma3)
ma_series4 = use_ema ? sma(src, ma4) : ema(src, ma4)
ma_series5 = use_ema ? sma(src, ma5) : ema(src, ma5)
ma_series6 = use_ema ? sma(src, ma6) : ema(src, ma6)
ma_series7 = use_ema ? sma(src, ma7) : ema(src, ma7)
ma_series8 = use_ema ? sma(src, ma8) : ema(src, ma8)

lma_series5 = use_ema ? sma(src, lma5) : ema(src, lma5)

//plot moving averages
p_ma1 = plot(ma_series1,title='MA-1',color=blend_color, linewidth=0)
p_ma2 = plot(ma_series2,title='MA-2',color=blend_color, linewidth=0)
p_ma3 = plot(ma_series3,title='MA-3',color=blend_color, linewidth=0)
p_ma4 = plot(ma_series4,title='MA-4',color=blend_color, linewidth=0)
p_ma5 = plot(ma_series5,title='MA-5',color=blend_color, linewidth=0)
p_ma6 = plot(ma_series6,title='MA-6',color=blend_color, linewidth=0)
p_ma7 = plot(ma_series7,title='MA-7',color=blend_color, linewidth=0)
p_ma8 = plot(ma_series8,title='MA-8',color=color.black, linewidth=2)

p_lma5 = plot(lma_series5,title='Long MA-5',color=color.orange, linewidth=2)

up_color = color.lime
down_color = color.maroon

fill(p_ma1, p_ma2, color=ma_series1 > ma_series2 ? color.new(up_color, transp=70) : color.new(down_color, transp=70))
fill(p_ma2, p_ma3, color=ma_series2 > ma_series3 ? color.new(up_color, transp=65) : color.new(down_color, transp=65))
fill(p_ma3, p_ma4, color=ma_series3 > ma_series4 ? color.new(up_color, transp=60) : color.new(down_color, transp=60))
fill(p_ma4, p_ma5, color=ma_series4 > ma_series5 ? color.new(up_color, transp=55) : color.new(down_color, transp=55))
fill(p_ma5, p_ma6, color=ma_series5 > ma_series6 ? color.new(up_color, transp=50) : color.new(down_color, transp=50))
fill(p_ma6, p_ma7, color=ma_series6 > ma_series7 ? color.new(up_color, transp=45) : color.new(down_color, transp=45))
fill(p_ma7, p_ma8, color=ma_series7 > ma_series8 ? color.new(up_color, transp=40) : color.new(down_color, transp=40))
