//@version=5
indicator(title="[TVT] Risk On/Off", shorttitle="TVT-RISK", overlay=false, precision=0)

// Credit: https://www.tradingview.com/v/z3iCKHxg/

//Safe Haven Demand:
shd1 = request.security("SPX", "D", (close - close[20]) / close * 100)
shd2 = request.security("ZB1!", "D", (close - close[20]) / close * 100)
shd = shd1 - shd2
// plot(shd, linewidth=2, color=color.fuchsia, transp=0)

//Stock Price Breadth:
spb1 = request.security("UVOL", "D", close)
spb2 = request.security("DVOL", "D", close)
spb3 = spb1 - spb2
ema19 = ta.ema(spb3, 19)
ema39 = ta.ema(spb3, 39)
osci = ema19 - ema39
spb = ta.cum(osci)
// plot(spb, linewidth=2, color=color.fuchsia, transp=0)

//Market Momentum:
mm1 = request.security("SPX", "D", close)
mm2 = request.security("SPX", "D", ta.sma(close, 125))
mm = (mm1 - mm2) / mm1 * 100
//plot(mm, linewidth=2, color=color.fuchsia, transp=0)

//Stock Price Strength:
sps1 = request.security("MAHN", "D", ta.ema(close, 5))
sps2 = request.security("MALN", "D", ta.ema(close, 5))
sps = ta.ema((sps1 - sps2) / (sps1 + sps2) * 100, 10)
//plot(sps, linewidth=2, color=color.fuchsia, transp=0)

//Put and Call Options:
pco = request.security("USI:PCC", "D", ta.sma(close, 5))
//plot(pco, linewidth=2, color=color.fuchsia, transp=0)

//Junk Bond Demand
jbd1 = request.security("Quandl:ML/USEY|0", "D", close)
jbd2 = request.security("Quandl:ML/USTRI|0", "D", close)
jbd = jbd2 - jbd1
//plot(jbd, linewidth=2, color=color.fuchsia, transp=0)

//Market Volatility:
mv = request.security("VIX", "D", close)
//plot(mv, linewidth=2, color=color.fuchsia, transp=0)

//Merge:
ind_shd = ta.percentrank(shd, 252)
//plot(shd1, linewidth=2, color=color.aqua, transp=0)
//plot(shd2, linewidth=2, color=color.navy, transp=0)
//plot(shd, linewidth=2, color=color.fuchsia, transp=0)
//plot(ind_shd, linewidth=2, color=color.black, transp=0)

ind_spb = ta.percentrank(spb, 252)
//plot(spb1, linewidth=2, color=color.aqua, transp=0)
//plot(spb2, linewidth=2, color=color.navy, transp=0)
//plot(spb, linewidth=2, color=color.fuchsia, transp=0)
//plot(ind_spb, linewidth=2, color=color.black, transp=0)

ind_mm = ta.percentrank(mm, 252)
//plot(mm1, linewidth=2, color=color.aqua, transp=0)
//plot(mm2, linewidth=2, color=color.navy, transp=0)
//plot(mm, linewidth=2, color=color.fuchsia, transp=0)
//plot(ind_mm, linewidth=2, color=color.black, transp=0)

ind_sps = ta.percentrank(sps, 252)
//plot(spb1, linewidth=2, color=color.aqua, transp=0)
//plot(spb2, linewidth=2, color=color.navy, transp=0)
//plot(spb, linewidth=2, color=color.fuchsia, transp=0)
//plot(ind_sps, linewidth=2, color=color.black, transp=0)

ind_pco = 100 - ta.percentrank(pco, 252)
//plot(spb1, linewidth=2, color=color.aqua, transp=0)
//plot(spb2, linewidth=2, color=color.navy, transp=0)
//plot(pco, linewidth=2, color=color.fuchsia, transp=0)
//plot(ind_pco, linewidth=2, color=color.black, transp=0)

ind_jbd = 100 - ta.percentrank(jbd, 252)
//ind_jbd = ta.percentrank(jbd, 252)
//plot(jbd1, linewidth=2, color=color.aqua, transp=0)
//plot(jbd2, linewidth=2, color=color.navy, transp=0)
//plot(jbd, linewidth=2, color=color.fuchsia, transp=0)
//plot(ind_jbd, linewidth=2, color=color.black, transp=0)

ind_mv = 100 - ta.percentrank(mv, 252)
//plot(jbd1, linewidth=2, color=color.aqua, transp=0)
//plot(jbd2, linewidth=2, color=color.navy, transp=0)
//plot(mv, linewidth=2, color=color.fuchsia, transp=0)
//plot(ind_mv, linewidth=2, color=color.black, transp=0)

//geo_fg = math.pow((ind_shd+1)(ind_spb+1)(ind_mm+1)(ind_sps+1)(ind_pco+1)(ind_jbd+1)(ind_mv+1), 0.14285714)
fg = (ind_shd + ind_spb + ind_mm + ind_sps + ind_pco + ind_jbd + ind_mv) / 7

// plot(ind_shd, color=color.new(#00FF00, 0), linewidth=1, title="Safe Haven Demand")
// plot(ind_spb, color=color.new(#88FF00, 0), linewidth=1, title="Stock Price Breadth")
// plot(ind_mm, color=color.new(#BBBB00, 0), linewidth=1, title="Market Momentum")
// plot(ind_sps, color=color.new(#FF8800, 0), linewidth=1, title="Stock Price Strength")
// plot(ind_pco, color=color.new(#FF0000, 0), linewidth=1, title="Put/Call Ratio")
// plot(ind_jbd, color=color.new(#FF0080, 0), linewidth=1, title="Junk Bond Demand")
// plot(ind_mv, color=color.new(#BB00BB, 0), linewidth=1, title="Market Volatility")

// Plotting the Fear and Greed Index with color condition
plot(fg, linewidth=2, color=(fg > 50 ? color.new(color.green, 0) : color.new(color.red, 0)))

hline(10, color=color.black, linestyle=hline.style_dotted, linewidth=1)
hline(80, color=color.black, linestyle=hline.style_dotted, linewidth=1)