//@version=4
study(title="[TVT] Multiple Moving Averages", shorttitle="TVT-MMA", overlay=true)

// === INPUTS ===
src = input(close)
use_ema = input(true, title="Use EMA over SMA?")
bb_mult = input(2.0, minval=0.001, maxval=50, title="BB Oversold/Overbought deviation")

// Short Moving Averages
ma1   = input(3,title='Short MA-1')
ma2   = input(8,title='Short MA-2')
ma3   = input(21,title='Short MA-3, Also used for BB')
ma4   = input(50,title='Short MA-4')

blend_color = color.white

ma_series1 = use_ema ? sma(src, ma1) : ema(src, ma1)
ma_series2 = use_ema ? sma(src, ma2) : ema(src, ma2)
ma_series3 = use_ema ? sma(src, ma3) : ema(src, ma3)
ma_series4 = use_ema ? sma(src, ma4) : ema(src, ma4)

//plot moving averages
p_ma1 = plot(ma_series1,title='MA-1',color=blend_color, linewidth=0)
p_ma2 = plot(ma_series2,title='MA-2',color=blend_color, linewidth=0)
p_ma3 = plot(ma_series3,title='MA-3',color=blend_color, linewidth=0)
p_ma4 = plot(ma_series4,title='MA-4',color=blend_color, linewidth=0)

up_color = color.lime
down_color = color.maroon

fill(p_ma1, p_ma2, color=ma_series1 > ma_series2 ? color.new(up_color, transp=70) : color.new(down_color, transp=70))
fill(p_ma2, p_ma3, color=ma_series2 > ma_series3 ? color.new(up_color, transp=55) : color.new(down_color, transp=55))
fill(p_ma3, p_ma4, color=ma_series3 > ma_series4 ? color.new(up_color, transp=30) : color.new(down_color, transp=30))

// BB Expansion
bb_stdev = bb_mult * stdev(src, ma3)
bb_upper = ma_series3 + bb_stdev
bb_lower = ma_series3 - bb_stdev

bgcolor((close > bb_upper) ? color.new(color.orange, 90) : na, title="Overbought")
bgcolor((close < bb_lower) ? color.new(color.orange, 90) : na, title="Oversold")

