//@version=5
indicator(title="[TVT] 3X Scale In Out", shorttitle="TVT-3X", overlay=true, timeframe="", timeframe_gaps=true)

// === INPUTS ===
src = input(close)
use_ema = input(false, title="Use EMA over SMA?")

// Short Moving Averages
ma1   = input(8,title='MA-1')
ma2   = input(21,title='MA-2')

blend_color = color.white

ma_series1 = use_ema ? ta.sma(src, ma1) : ta.ema(src, ma1)
ma_series2 = use_ema ? ta.sma(src, ma2) : ta.ema(src, ma2)

//plot moving averages
p_ma1 = plot(ma_series1,title='MA-1',color=color.blue, linewidth=1)
p_ma2 = plot(ma_series2,title='MA-2',color=color.maroon, linewidth=1)

up_color = color.lime
down_color = color.maroon

fill(p_ma1, p_ma2, color=ma_series1 > ma_series2 ? color.new(color.lime, 70) : color.new(color.maroon, 70))
