import os

from dotenv import load_dotenv

load_dotenv()

# Crypto
EXCHANGE_API_KEY = os.getenv("EXCHANGE_API_KEY")
EXCHANGE_API_SECRET = os.getenv("EXCHANGE_API_SECRET")
EXCHANGE = os.getenv("EXCHANGE")

# Telegram

# PERSONAL_CHAT_ID = os.getenv("CHAT_ID")
DEFAULT_BOT_TOKEN = os.getenv("BOT_TOKEN")
GROUP_CHAT_ID = os.getenv("GROUP_CHAT_ID")
TELEGRAM_STOCK_RIDER_BOT = os.getenv("TELEGRAM_STOCK_RIDER_BOT")
TELEGRAM_THETA_GANG_BOT = os.getenv("TELEGRAM_THETA_GANG_BOT")
TELEGRAM_STOCK_ALERT_BOT = os.getenv("TELEGRAM_STOCK_ALERT_BOT")

# Twitter
TWITTER_CONSUMER_KEY = os.getenv("TWITTER_CONSUMER_KEY")
TWITTER_CONSUMER_SECRET = os.getenv("TWITTER_CONSUMER_SECRET")
TWITTER_ACCESS_TOKEN_KEY = os.getenv("TWITTER_ACCESS_TOKEN_KEY")
TWITTER_ACCESS_TOKEN_SECRET = os.getenv("TWITTER_ACCESS_TOKEN_SECRET")

# Tradier
TRADIER_BASE_URL = os.getenv("TRADIER_BASE_URL")
TRADIER_TOKEN = os.getenv("TRADIER_TOKEN")

# ACCOUNT
TRADING_ACCOUNT_VALUE = int(os.getenv("TRADING_ACCOUNT_VALUE"))
TRADING_RISK_FACTOR = float(os.getenv("TRADING_RISK_FACTOR")) / 100
TRADING_MAX_DD = float(os.getenv("TRADING_MAX_DD_PCT")) / 100
PROFIT_TARGET_PCT = float(os.getenv("PROFIT_TARGET_PCT")) / 100
STOP_LOSS_PCT = float(os.getenv("STOP_LOSS_PCT")) / 100

# CoinMarketCap
COIN_MARKET_CAP_API_KEY = os.getenv("COIN_MARKET_CAP_API_KEY")
