market_sectors = (
    "XHB",
    "XLC",
    "XLY",
    "XLP",
    "XLE",
    "XLF",
    "XLV",
    "XLI",
    "XLB",
    "XLRE",
    "XLK",
    "XME",
    "XOP",
    "GDX",
    "IYR",
    "XLU",
)

macro_etfs = {
    "SPY": "S&P 500 Index",
    "DIA": "Dow Jones Industrials Index",
    "IWM": "Russell 2000 Index",
    "QQQ": "Nasdaq Index",
    "IJH": "S&P 500 Mid Cap",
    "IJR": "S&P 500 Small Cap",
    "IWC": "Micro Cap",
    "TLT": "20+ Years Treasuries",
    "EEM": "Emerging Markets",
    "EWJ": "Japan",
    "EWW": "Mexico",
    "EWZ": "Brazil",
    "EWY": "Korea",
    "FXI": "China",
    "BKF": "BRIC (Brazil, Russia, India, China)",
    "RSX": "Russia",
    "EWG": "Germany",
    "EWU": "United Kingdom",
    "EFA": "Europe, Asia, SA",
    "GBTC": "Bitcoin",
    "GLD": "Gold",
    "SLV": "Silver",
    "UNG": "Natural Gas",
    "USO": "Oil",
    "DBA": "Agriculture",
    "UUP": "US Dollar",
    "FXE": "Euro",
    "FXB": "British Pound",
    "FXY": "Japanese Yen",
    "FALN": "High Yield Corporate Bonds",
    "XHB": "HomeBuilders",
    "XLC": "Communication Services",
    "XLY": "Consumer Cyclical",
    "XLP": "Consumer Defensive",
    "XLE": "Energy",
    "XLF": "Financial Services",
    "XLV": "Healthcare",
    "XLI": "Industrials",
    "XLB": "Basic Materials",
    "XLK": "Technology",
    "XME": "Metals and Mining",
    "XOP": "Oil & Gas Exploration",
    "GDX": "Gold Miners",
    "IYR": "Real Estate",
    "XLU": "Utilities",
}
